name-template: 'next version'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: '⚠️ Breaking Changes' 
    labels:
      - 'feat!'
  - title: '🚀 New Features'
    labels:
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
  - title: '🧰 Maintenance'
    labels:
      - 'refactor'
      - 'docs'
exclude-labels:
  - 'chore'
  - 'test'
  - 'style'
  - 'cosm'
  - 'build'
change-template: '* $TITLE (#$NUMBER)'
template: |
  $CHANGES
